### ISSUE TITLE
Improve 'running as root' message to be more prescriptive

### ISSUE THREAD

**Issue by vin-yu** [Microsoft/dbfs#10]
When running DBFS as root, the message of "Running as root opens unwanted security holes" should be improved to be prescriptive. Something along the lines of
"DBFS does not require root privileges. Please exit root before starting DBFS"

https://twitter.com/smooth1x1/status/868535038962544640 

![root msg](https://cloud.githubusercontent.com/assets/7897410/26606201/de898cd8-4545-11e7-9f6b-372f76daa1bc.jpg)

**Comment by aditya-shantanu** [comment]
Fixed with commit - 9ce08a0.
